version: '3'  # compose file syntax

services:
  mariadb:
    container_name: test-mariadb
    hostname: test-mariadb
    image: docker-test:mariadb
    build:
      context: ./mariadb
      dockerfile: DockerFile
    environment:
      MARIADB_ROOT_PASSWORD: root
    volumes:
      - ./mariadb/initdb.d:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    networks:
      - global
  
  backend-server:
    container_name: test-backend-server
    hostname: test-backend-server
    image: docker-test:backend-server
    build:
      context: ./backend-server
      dockerfile: DockerFile
    volumes:
      - ./backend-server/src:/src
    ports:
      - 8000:8000
    networks:
      - global
      - dev-backend

  jupyter-server:
    container_name: test-jupyter-server
    hostname: test-jupyter-server
    image: docker-test:jupyter-server
    build:
      context: ./jupyter-server
      dockerfile: DockerFile
    volumes:
      - ./jupyter-server/src:/src
    ports:
      - 8880:8888
    networks:
      - global
      - dev-backend

networks:
  global:
  dev-backend:
    driver: bridge