version: '1'

services:
  test-container:  # services 이름
    container_name: test-container
    hostname: test-container
    build:
      context: .
      dockerfile: DockerFile
    volumes:
      - ./src:/src  # code 싱크 맞추기(=copy) ex) {local_path}:{container_path}

  postgress:
    container_name: postgres
    hostname: postgres
    image: postgres:13  # docker image file 이미 있는 경우 (from hub.docker.com)
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - 8080:8080  # conainer간의 port 연결